### PR TITLE
add nginx

### PR DESCRIPTION
**Pull request by Hakob9**
Install nginx by using script in 'nginx-install.sh' file and check if it runs properly

### CODE REVIEW

**Review by sargsyan1986 — CHANGES_REQUESTED** [review]
add more options
check nginx existing 
and after that instoll it whit "-y" flag
befor update apt

**Review by mkrtchyan-t — CHANGES_REQUESTED** [review]
You should also install curl for starting nginx server
```
apt install curl -y
```

**Comment by Hakob9** [comment]
I checked the script and improved it by adding some changes. Please review.

**Review by mkrtchyan-t — APPROVED** [review]
work fine to me!

**Review by Frida199 — APPROVED** [review]
ok

**Review by sargsyan1986 — APPROVED** [review]

**Comment by mkrtchyan-t** [comment]
you can now merge it !

**Pull request merged**
